
CREATE TABLE IF NOT EXISTS usuaris (
  id BIGINT AUTO_INCREMENT PRIMARY KEY UNIQUE,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  ultimAcces TIMESTAMP NULL,
  dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  image_path VARCHAR(500) NULL
  
);
